name: Qodana Static Analysis

on:
  push:
    branches: [ main, 6-ts2-cicd]
  pull_request:
    branches: [ main, 6-ts2-cicd]

jobs:
  qodana:
    name: Qodana Static Analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Qodana scan
        uses: JetBrains/qodana-action@v2024.2.6
        with:
          upload-result: true
          results-dir: qodana